### ISSUE TITLE
Move the validation logic for student creation into model

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/classroom-mode#51]
Currently, when you create a new student, the server/routes/addStudent.js file handles all of the creation logic, including validating the student object fields (like email, username, etc).  This is not a great design.  Ideally, the validation for the student object fields should happen inside of a student model instead.  

In this way, we will have a separation of concerns between addStudent.js (which should be our controller) and the student model.

**Comment by imcodingideas** [comment]
I'm currently refactoring this.

**Comment by user512** [comment]
Closing because #62 took care of this.
