### ISSUE TITLE
Teacher can remove student from class table

### ISSUE THREAD

**Issue by user512** [freeCodeCamp/classroom-mode#58]
Refer to https://projects.invisionapp.com/share/J3C03W2SX#/screens/237080322

Nice to have: Confirmation msg for user

**Comment by imcodingideas** [comment]
Im working on this now.

**Comment by imcodingideas** [comment]
@user512 can you assign this to me?

**Comment by user512** [comment]
Github won't let me assign this to you so I am assigning to myself to hold this for you.

**Comment by imcodingideas** [comment]
Hey,

I've been working on the CRUD for the student list.

<img width="298" alt="Client File Changes" src="https://user-images.githubusercontent.com/5374985/39231524-36a8fd22-481f-11e8-8f51-e93e5f6c238b.png">

I know you said you wanted to work on this but let me define this better! Maybe you can fix the backend tests?
