### ISSUE TITLE
Teacher can edit students 

### ISSUE THREAD

**Issue by user512** [freeCodeCamp/classroom-mode#59]
Refer https://projects.invisionapp.com/share/J3C03W2SX#/screens/237080322

Nice to have: Modal to edit students?

**Comment by AryanJ-NYC** [comment]
@user512 Is anyone doing this story? If not, I can do it.

**Comment by user512** [comment]
Sounds great, would be great if you can also add test to maintain good test coverage and make sure build pass, thanks for the help @AryanJ-NYC
