### ISSUE TITLE
Goals For Classroom Mode

### ISSUE THREAD

**Issue by imcodingideas** [freeCodeCamp/classroom-mode#63]
Hello,

I've spent some time today working on this which is awesome. However; I still don't know what the big picture for this project is? 

Reviewing: https://projects.invisionapp.com/share/J3C03W2SX#/screens/237080318 I can see maybe there is a integration with FreeCodeCamp and if I wanted to mentor 10 students I could become a `teacher` and do code reviews?

**Comment by user512** [comment]
Hello @imcodingideas, thank you for your work and great question.

This project is intended to provide a visual presentation for teacher to keep track of their students' progress FreeCodeCamp. We noticed there are teachers assigning FreeCodeCamp coding exercise to their students but there isn't an easy way to keep track of students' progress.

@utsab and @udfood did some interviews and found out teachers would like to view data like student's day inactive data and student trial and error data to determine if students need help with a particular concept.

At this point we are trying to finish and refine the class table and get teacher feedback before moving forward with the potential FreeCodeCamp integration.

**Comment by imcodingideas** [comment]
Awesome, something like this needs to be in the readme. I will continue today.
