### ISSUE TITLE
Promote to Contributor. 

### ISSUE THREAD

**Issue by imcodingideas** [freeCodeCamp/classroom-mode#68]
Hello,

Few things. My blocker to get some work done is I cannot merge in my Pull Requests. I've clearly shown some interest in this project.

I want to ask if I could be a Contributor on this project. Whats the best way we can communicate as a team?

**Comment by user512** [comment]
I believe @utsab is the owner for this repo and he can add you as a contributor.
He is currently on vacation now but I can help you merge in your code as we move alone.

**Comment by user512** [comment]
@QuincyLarson can you add @imcodingideas as a collaborator?
I believe he is leading this codebase in a great direction, by adding him as a collaborator, he can work much faster.

**Comment by QuincyLarson** [comment]
@user512 @imcodingideas Yes - @utsab is the most knowledgable person for this repo. I haven't taken a look at this project in several months, and don't know about the state of the codebase or the user stories. 

I've added @imcodingideas as a contributor to this repo and given him write permission.

@imcodingideas Thanks for your help with this! We are actively working on https://github.com/freeCodeCamp/open-api which is our GraphQL API that should make it much easier to get data from freeCodeCamp's databases.

**Comment by imcodingideas** [comment]
Thanks so much @QuincyLarson and @user512 - I'm here working pretty hard moving this to mobx. I added react router, mobx, services.

**Comment by utsab** [comment]
Hi @imcodingideas, thanks for your interest in this project.  I look forward to looking through your commits once I get back from my trip which will be on Monday. 

The best way to communicate with us is to get on our slack channel.  Can you email me at utsab.k.saha@gmail.com?  I'll add you to the group. 

One request for you:  A big part of this project is to create a great learning environment for less experienced developers whom we work with as apprentices.  If you are introducing new technologies or refactoring the code base, can you clearly document what you did and why you did it?   We meet as as group several times  a week to code together (from 8pm - 9pm PST usually).  It would be great if you could come by and present the changes you are making so we can all learn from it.

**Comment by imcodingideas** [comment]
@QuincyLarson
